
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

import type { IContentItem, IContentItemElements, IDeliveryClient } from "@kontent-ai/delivery-sdk";
import type {
  ContentTypeCodenames,
  CollectionCodenames,
  LanguageCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames,
  ElementCodenames,
  TaxonomyCodenames,
} from "./delivery.codenames.ts";

/**
 * Core content type used in favor of default 'IContentItem'
 */
export type CoreContentType<
  TElementCodenames extends string = string,
  TElements extends IContentItemElements<TElementCodenames> = IContentItemElements<TElementCodenames>,
  TContentTypeCodename extends ContentTypeCodenames = ContentTypeCodenames,
> = IContentItem<
  TElements,
  TContentTypeCodename,
  LanguageCodenames,
  CollectionCodenames,
  WorkflowCodenames,
  WorkflowStepCodenames
>;

/**
 * Core types for 'IDeliveryClient'
 */
export type CoreClientTypes = {
  readonly collectionCodenames: CollectionCodenames;
  readonly contentItemType: CoreContentType;
  readonly contentTypeCodenames: ContentTypeCodenames;
  readonly elementCodenames: ElementCodenames;
  readonly languageCodenames: LanguageCodenames;
  readonly taxonomyCodenames: TaxonomyCodenames;
  readonly workflowCodenames: WorkflowCodenames;
  readonly worfklowStepCodenames: WorkflowStepCodenames;
};

/**
 * Typed delivery client in favor of default 'IDeliveryClient'
 */
export type CoreDeliveryClient = IDeliveryClient<CoreClientTypes>;
