
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

/**
 * Type representing all languages
 */
export type LanguageCodenames = "de-DE" | "default" | "es-ES";

/**
 * Type representing all content types
 */
export type ContentTypeCodenames =
  | "article"
  | "blog_post"
  | "call_to_action"
  | "disclaimer"
  | "event"
  | "fact_sectional"
  | "feature"
  | "hero_button"
  | "landing_page"
  | "page__copy_"
  | "page"
  | "percentage_fact"
  | "person"
  | "service"
  | "success_story"
  | "video";

/**
 * Type representing all collections
 */
export type CollectionCodenames =
  | "academic_content"
  | "boulevard"
  | "default"
  | "marketing_resources"
  | "operations"
  | "patient_resources";

/**
 * Type representing all workflows
 */
export type WorkflowCodenames = "academic_resources" | "biographies" | "default" | "patient_resources";

/**
 * Type representing all taxonomies
 */
export type TaxonomyCodenames =
  | "article_type"
  | "blog_post_tags"
  | "event_topic"
  | "event_type"
  | "general_healthcare_topics"
  | "industry_tags"
  | "medical_specialties";

/**
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames =
  | "archived"
  | "copy_review"
  | "draft_97d445e"
  | "draft_a8b162c"
  | "draft_b242d4d"
  | "draft"
  | "legal_review"
  | "marketing_review"
  | "medical_review"
  | "peer_review"
  | "published"
  | "reviewed_1778942"
  | "reviewed"
  | "scheduled"
  | "staff_member_review"
  | "translation";

/**
 * Type representing all element codenames across all content types
 */
export type ElementCodenames =
  | "article_type"
  | "author"
  | "autoplay"
  | "biography"
  | "blog_post_tags"
  | "body_copy"
  | "body"
  | "button_label"
  | "button_link"
  | "button_text"
  | "caption"
  | "card_image"
  | "case_study_image"
  | "case_study_pdf"
  | "description"
  | "disclaimer"
  | "email"
  | "end_date"
  | "event_topic"
  | "event_type"
  | "feature_body"
  | "feature_title"
  | "featured_content"
  | "first_name"
  | "guidelines"
  | "headline"
  | "hero_image"
  | "image_position"
  | "image"
  | "industry_tags"
  | "introduction"
  | "job_title"
  | "label"
  | "medical_specialties"
  | "metadata__description"
  | "metadata__keywords"
  | "metadata__title"
  | "metadata"
  | "name"
  | "page"
  | "percentage_facts"
  | "percentage_value"
  | "phone"
  | "publish_date"
  | "related_articles"
  | "start_date"
  | "style"
  | "subheadline"
  | "subpages"
  | "summary"
  | "team"
  | "title"
  | "topics"
  | "type"
  | "url_slug"
  | "url"
  | "video_link"
  | "website";
