
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Blog Post Tags
 *
 * Codename: blog_post_tags
 * Id: e45a4b56-17fe-4c17-9969-069e71405e0e
 */
export const blogPostTagsValues = [
  "business_tips",
  "client_experience",
  "front_desk",
  "industry_spotlight",
  "industry_trends",
  "leadership",
  "marketing",
  "online_booking",
  "payments",
  "payroll",
  "recruitment",
  "reporting",
  "best_practice",
] as const;

/**
 * Type representing Blog Post Tags taxonomy
 *
 * Codename: blog_post_tags
 * Id: e45a4b56-17fe-4c17-9969-069e71405e0e
 */
export type BlogPostTags = (typeof blogPostTagsValues)[number];

/**
 * Type guard for Blog Post Tags
 *
 * Codename: blog_post_tags
 * Id: e45a4b56-17fe-4c17-9969-069e71405e0e
 */
export function isBlogPostTags(value: string | undefined | null): value is BlogPostTags {
  return typeof value === "string" && (blogPostTagsValues as readonly string[]).includes(value);
}
