
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for General Healthcare Topics
 *
 * Codename: general_healthcare_topics
 * Id: 98a310bc-4d8f-4a58-9304-5bee40766382
 */
export const generalHealthcareTopicsValues = [
  "healthcare_policy___regulations",
  "medical_research___innovations",
  "health___wellness",
  "preventative_care",
  "public_health",
] as const;

/**
 * Type representing General Healthcare Topics taxonomy
 *
 * Codename: general_healthcare_topics
 * Id: 98a310bc-4d8f-4a58-9304-5bee40766382
 */
export type GeneralHealthcareTopics = (typeof generalHealthcareTopicsValues)[number];

/**
 * Type guard for General Healthcare Topics
 *
 * Codename: general_healthcare_topics
 * Id: 98a310bc-4d8f-4a58-9304-5bee40766382
 */
export function isGeneralHealthcareTopics(value: string | undefined | null): value is GeneralHealthcareTopics {
  return typeof value === "string" && (generalHealthcareTopicsValues as readonly string[]).includes(value);
}
