
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Industry Tags
 *
 * Codename: industry_tags
 * Id: 1af91b38-68bc-4d79-abb8-f2c15c581386
 */
export const industryTagsValues = ["medspa", "salon", "spa", "barber", "massage", "nail_salon"] as const;

/**
 * Type representing Industry Tags taxonomy
 *
 * Codename: industry_tags
 * Id: 1af91b38-68bc-4d79-abb8-f2c15c581386
 */
export type IndustryTags = (typeof industryTagsValues)[number];

/**
 * Type guard for Industry Tags
 *
 * Codename: industry_tags
 * Id: 1af91b38-68bc-4d79-abb8-f2c15c581386
 */
export function isIndustryTags(value: string | undefined | null): value is IndustryTags {
  return typeof value === "string" && (industryTagsValues as readonly string[]).includes(value);
}
