
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { BlogPostTags, IndustryTags } from "../taxonomies/index.ts";
import type { CoreContentType } from "../system/index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";
import type { Person } from "./index.ts";

/**
 * ✍🏼 Blog Post
 *
 * Id: 336302c0-0634-4974-b33b-8c7b0469e837
 * Codename: blog_post
 */
export type BlogPost = CoreContentType<
  BlogPostElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: true
     * Codename: title
     * Id: 72869e6e-2822-4e81-944a-d90b3148ce4a
     */
    readonly title: Elements.TextElement;
    /**
     * Image
     *
     * Type: asset
     * Required: true
     * Codename: image
     * Id: 1361b589-f40e-4c4a-b219-62a0f3f5a8c0
     */
    readonly image: Elements.AssetsElement;
    /**
     * Body
     *
     * Type: rich_text
     * Required: true
     * Codename: body
     * Id: e74bc043-0613-4554-8fb5-4d03a42c61a5
     */
    readonly body: Elements.RichTextElement<CoreContentType>;
    /**
     * Summary
     *
     * Type: text
     * Required: false
     * Codename: summary
     * Id: a555e901-79d3-4585-8c7b-44c149da9803
     * Guidelines: This should be a short paragraph that captures the main point of a blog post
     */
    readonly summary: Elements.TextElement;
    /**
     * Author
     *
     * Type: modular_content
     * Required: false
     * Codename: author
     * Id: d245b2bc-8e7c-4302-b87b-f112c819c9e6
     */
    readonly author: Elements.LinkedItemsElement<Person>;
    /**
     * Blog Post Tags
     *
     * Type: taxonomy
     * Required: false
     * Codename: blog_post_tags
     * Id: 326aab4c-97eb-4556-afcc-bae0b6c949e9
     */
    readonly blog_post_tags: Elements.TaxonomyElement<BlogPostTags, "blog_post_tags">;
    /**
     * Industry Tags
     *
     * Type: taxonomy
     * Required: false
     * Codename: industry_tags
     * Id: 845537e5-cb33-4e2a-8231-c7d87c480eeb
     */
    readonly industry_tags: Elements.TaxonomyElement<IndustryTags, "industry_tags">;
    /**
     * URL slug
     *
     * Type: url_slug
     * Required: true
     * Codename: url_slug
     * Id: cfdddb6d-ae75-431b-ac02-af463468d86b
     */
    readonly url_slug: Elements.UrlSlugElement;
  } & Metadata,
  "blog_post"
>;

/**
 * Type representing all available element codenames for ✍🏼 Blog Post
 */
export type BlogPostElementCodenames =
  | "title"
  | "image"
  | "body"
  | "summary"
  | "author"
  | "blog_post_tags"
  | "industry_tags"
  | "metadata__title"
  | "metadata__keywords"
  | "metadata__description"
  | "url_slug";

/**
 * Type guard for ✍🏼 Blog Post
 *
 * Id: 336302c0-0634-4974-b33b-8c7b0469e837
 * Codename: blog_post
 */
export function isBlogPost(item: CoreContentType | undefined | null): item is BlogPost {
  return item?.system?.type === "blog_post";
}
