
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { PercentageFact } from "./index.ts";

/**
 * Fact Sectional
 *
 * Id: baa15a64-566a-4d76-aa6c-23c5efa1c467
 * Codename: fact_sectional
 */
export type FactSectional = CoreContentType<
  FactSectionalElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: false
     * Codename: title
     * Id: e022e6b3-11ad-451a-916b-2fd39af77eac
     */
    readonly title: Elements.TextElement;
    /**
     * Percentage Facts
     *
     * Type: modular_content
     * Required: false
     * Codename: percentage_facts
     * Id: 0bd8d558-1514-498b-a9d6-44f60a816454
     */
    readonly percentage_facts: Elements.LinkedItemsElement<PercentageFact>;
    /**
     * Disclaimer
     *
     * Type: text
     * Required: false
     * Codename: disclaimer
     * Id: 76c39870-f7b5-445b-8fd4-5b0478ad02a1
     */
    readonly disclaimer: Elements.TextElement;
    /**
     * Style
     *
     * Type: multiple_choice
     * Required: false
     * Codename: style
     * Id: db3eec77-515d-458d-ba18-12218afff7d7
     */
    readonly style: Elements.MultipleChoiceElement<"black" | "gold">;
  },
  "fact_sectional"
>;

/**
 * Type representing all available element codenames for Fact Sectional
 */
export type FactSectionalElementCodenames = "title" | "percentage_facts" | "disclaimer" | "style";

/**
 * Type guard for Fact Sectional
 *
 * Id: baa15a64-566a-4d76-aa6c-23c5efa1c467
 * Codename: fact_sectional
 */
export function isFactSectional(item: CoreContentType | undefined | null): item is FactSectional {
  return item?.system?.type === "fact_sectional";
}
