
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * ✅ Feature
 *
 * Id: ef6de82e-9fdd-40e2-99bd-291930302544
 * Codename: feature
 */
export type Feature = CoreContentType<
  FeatureElementCodenames,
  {
    /**
     * Feature Title
     *
     * Type: text
     * Required: false
     * Codename: feature_title
     * Id: 17d39206-44bd-4d1e-bc7b-7bc5f37fc118
     */
    readonly feature_title: Elements.TextElement;
    /**
     * Feature Body
     *
     * Type: text
     * Required: false
     * Codename: feature_body
     * Id: b6592986-aac1-4003-9682-6b961a8e0c13
     */
    readonly feature_body: Elements.TextElement;
  },
  "feature"
>;

/**
 * Type representing all available element codenames for ✅ Feature
 */
export type FeatureElementCodenames = "feature_title" | "feature_body";

/**
 * Type guard for ✅ Feature
 *
 * Id: ef6de82e-9fdd-40e2-99bd-291930302544
 * Codename: feature
 */
export function isFeature(item: CoreContentType | undefined | null): item is Feature {
  return item?.system?.type === "feature";
}
