
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Page } from "./index.ts";

/**
 * Hero Button
 *
 * Id: 1b4af418-989a-45c9-b8cf-5bdbc3281f8e
 * Codename: hero_button
 */
export type HeroButton = CoreContentType<
  HeroButtonElementCodenames,
  {
    /**
     * Button Text
     *
     * Type: text
     * Required: false
     * Codename: button_text
     * Id: 8dd45e4a-b02b-405b-a75c-622f3e231d34
     */
    readonly button_text: Elements.TextElement;
    /**
     * Page
     *
     * Type: modular_content
     * Required: false
     * Codename: page
     * Id: 0dec747b-c9d2-423f-96c2-23dc1ef8bd44
     */
    readonly page: Elements.LinkedItemsElement<Page>;
  },
  "hero_button"
>;

/**
 * Type representing all available element codenames for Hero Button
 */
export type HeroButtonElementCodenames = "button_text" | "page";

/**
 * Type guard for Hero Button
 *
 * Id: 1b4af418-989a-45c9-b8cf-5bdbc3281f8e
 * Codename: hero_button
 */
export function isHeroButton(item: CoreContentType | undefined | null): item is HeroButton {
  return item?.system?.type === "hero_button";
}
