
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";
import type { Video, Disclaimer, CallToAction } from "./index.ts";

/**
 * Customer Success Stories Page
 *
 * Id: 670df230-4109-458f-93ab-7fb5d167addb
 * Codename: page__copy_
 */
export type CustomerSuccessStoriesPage = CoreContentType<
  CustomerSuccessStoriesPageElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: true
     * Codename: headline
     * Id: 47f7f606-5eec-4959-af4a-6756e1c56bab
     */
    readonly headline: Elements.TextElement;
    /**
     * Subheadline
     *
     * Type: text
     * Required: true
     * Codename: subheadline
     * Id: 66f22984-6adb-4552-b3da-cb3a566fb5dd
     */
    readonly subheadline: Elements.TextElement;
    /**
     * Body
     *
     * Type: rich_text
     * Required: false
     * Codename: body
     * Id: 3c0456b5-9609-4450-9f5a-66c3e8cdb34c
     */
    readonly body: Elements.RichTextElement<Video | Disclaimer | CallToAction>;
    /**
     * URL
     *
     * Type: url_slug
     * Required: true
     * Codename: url
     * Id: de66126f-63a9-4c26-9966-cffc30cae92a
     */
    readonly url: Elements.UrlSlugElement;
  } & Metadata,
  "page__copy_"
>;

/**
 * Type representing all available element codenames for Customer Success Stories Page
 */
export type CustomerSuccessStoriesPageElementCodenames =
  | "headline"
  | "subheadline"
  | "body"
  | "metadata__title"
  | "metadata__keywords"
  | "metadata__description"
  | "url";

/**
 * Type guard for Customer Success Stories Page
 *
 * Id: 670df230-4109-458f-93ab-7fb5d167addb
 * Codename: page__copy_
 */
export function isCustomerSuccessStoriesPage(
  item: CoreContentType | undefined | null,
): item is CustomerSuccessStoriesPage {
  return item?.system?.type === "page__copy_";
}
