
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Percentage Fact
 *
 * Id: 229a1c65-0f30-4c17-ae17-5be84cef13ab
 * Codename: percentage_fact
 */
export type PercentageFact = CoreContentType<
  PercentageFactElementCodenames,
  {
    /**
     * Percentage Value
     *
     * Type: number
     * Required: false
     * Codename: percentage_value
     * Id: fb56be28-bea5-4a0b-afd6-924abeb004a2
     */
    readonly percentage_value: Elements.NumberElement;
    /**
     * Label
     *
     * Type: text
     * Required: false
     * Codename: label
     * Id: 72b13efd-9de6-4a23-9e0b-fc94beb8633d
     */
    readonly label: Elements.TextElement;
  },
  "percentage_fact"
>;

/**
 * Type representing all available element codenames for Percentage Fact
 */
export type PercentageFactElementCodenames = "percentage_value" | "label";

/**
 * Type guard for Percentage Fact
 *
 * Id: 229a1c65-0f30-4c17-ae17-5be84cef13ab
 * Codename: percentage_fact
 */
export function isPercentageFact(item: CoreContentType | undefined | null): item is PercentageFact {
  return item?.system?.type === "percentage_fact";
}
