
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * 🙌🏼 Success Story
 *
 * Id: 3ccea84d-6d68-42b9-87fe-cc280b22677b
 * Codename: success_story
 */
export type SuccessStory = CoreContentType<
  SuccessStoryElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: false
     * Codename: title
     * Id: b428142f-3b6a-4984-a590-410c506df246
     */
    readonly title: Elements.TextElement;
    /**
     * Body
     *
     * Type: rich_text
     * Required: false
     * Codename: body
     * Id: 1544de02-1fa2-472f-aa5e-b538b09002be
     */
    readonly body: Elements.RichTextElement<CoreContentType>;
    /**
     * Case Study Image
     *
     * Type: asset
     * Required: false
     * Codename: case_study_image
     * Id: 74153787-4c47-466e-8017-6ef461f16d68
     * Guidelines: This is the image of the case study, not the case study itself
     */
    readonly case_study_image: Elements.AssetsElement;
    /**
     * Case Study PDF
     *
     * Type: asset
     * Required: false
     * Codename: case_study_pdf
     * Id: 2a4e44c9-5136-44b6-8a92-b75f570566ef
     */
    readonly case_study_pdf: Elements.AssetsElement;
    /**
     * Card Image
     *
     * Type: asset
     * Required: false
     * Codename: card_image
     * Id: c30fa2ce-c912-4fc9-a7f2-1d97d38c11f0
     * Guidelines: This is the image that will be used on the Customer Success Stories Page
     */
    readonly card_image: Elements.AssetsElement;
  },
  "success_story"
>;

/**
 * Type representing all available element codenames for 🙌🏼 Success Story
 */
export type SuccessStoryElementCodenames = "title" | "body" | "case_study_image" | "case_study_pdf" | "card_image";

/**
 * Type guard for 🙌🏼 Success Story
 *
 * Id: 3ccea84d-6d68-42b9-87fe-cc280b22677b
 * Codename: success_story
 */
export function isSuccessStory(item: CoreContentType | undefined | null): item is SuccessStory {
  return item?.system?.type === "success_story";
}
