
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Boulevard
* Environment: Production
* Id: 2a156019-e825-0006-1d2b-627d3d7f82f7
* 
* -------------------------------------------------------------------------------
**/

export * from "./metadata.ts";
